kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.snowflakeServiceName }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.snowflakeStatefulSetName }}"
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
