kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.snowflakeServiceName }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.snowflakeStatefulsetName }}"
  ports:
    - port: {{ .Values.port | int }}
      targetPort: {{ .Values.targetPort | int }}
      nodePort: {{ .Values.nodePort | int }}
