kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: "{{ .Values.snowflakeStatefulsetName }}"
spec:
  serviceName: "{{ .Values.snowflakeServiceName }}"
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Values.snowflakeStatefulsetName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.snowflakeStatefulsetName }}"
    spec:
      containers:
        - name: "{{ .Values.snowflakeStatefulsetName }}"
          image: "{{ .Values.imageName }}:{{ .Values.imageTag }}"
          ports:
            - containerPort: 8000
          env:
            - name: "{{ .Values.env.name.key }}"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /snowflake/health
              port: {{ .Values.port | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
