kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: "{{ .Values.snowflakeStatefulSetName }}"
spec:
  serviceName: "{{ .Values.snowflakeServiceName }}"
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Values.snowflakeStatefulSetName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.snowflakeStatefulSetName }}"
    spec:
      containers:
        - name: "{{ .Values.snowflakeStatefulSetName }}"
          image: snowflake:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: "{{ .Values.env.name.key }}"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "echo $SNOWFLAKE_MACHINE_ID" ]
          livenessProbe:
            httpGet:
              path: /snowflake/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
