kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.snowflakeservicename }}"
spec:
  type: NodePort
  selector:
    app: snowflake-statefulset
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
